<?php
/**
 * Route
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Train routing & analytics API
 *
 * API pour router un train d'une station A à B sur un réseau, calculer la distance parcourue et fournir des statistiques agrégées par code analytique.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: n.girardet@mob.ch
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * Route Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Route implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Route';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'string',
        'from_station_id' => 'string',
        'to_station_id' => 'string',
        'analytic_code' => 'string',
        'distance_km' => 'float',
        'path' => 'string[]',
        'created_at' => '\DateTime'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => null,
        'from_station_id' => null,
        'to_station_id' => null,
        'analytic_code' => null,
        'distance_km' => 'double',
        'path' => null,
        'created_at' => 'date-time'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'id' => false,
        'from_station_id' => false,
        'to_station_id' => false,
        'analytic_code' => false,
        'distance_km' => false,
        'path' => false,
        'created_at' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'from_station_id' => 'fromStationId',
        'to_station_id' => 'toStationId',
        'analytic_code' => 'analyticCode',
        'distance_km' => 'distanceKm',
        'path' => 'path',
        'created_at' => 'createdAt'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'from_station_id' => 'setFromStationId',
        'to_station_id' => 'setToStationId',
        'analytic_code' => 'setAnalyticCode',
        'distance_km' => 'setDistanceKm',
        'path' => 'setPath',
        'created_at' => 'setCreatedAt'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'from_station_id' => 'getFromStationId',
        'to_station_id' => 'getToStationId',
        'analytic_code' => 'getAnalyticCode',
        'distance_km' => 'getDistanceKm',
        'path' => 'getPath',
        'created_at' => 'getCreatedAt'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('from_station_id', $data ?? [], null);
        $this->setIfExists('to_station_id', $data ?? [], null);
        $this->setIfExists('analytic_code', $data ?? [], null);
        $this->setIfExists('distance_km', $data ?? [], null);
        $this->setIfExists('path', $data ?? [], null);
        $this->setIfExists('created_at', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['from_station_id'] === null) {
            $invalidProperties[] = "'from_station_id' can't be null";
        }
        if ($this->container['to_station_id'] === null) {
            $invalidProperties[] = "'to_station_id' can't be null";
        }
        if ($this->container['analytic_code'] === null) {
            $invalidProperties[] = "'analytic_code' can't be null";
        }
        if ($this->container['distance_km'] === null) {
            $invalidProperties[] = "'distance_km' can't be null";
        }
        if (($this->container['distance_km'] < 0)) {
            $invalidProperties[] = "invalid value for 'distance_km', must be bigger than or equal to 0.";
        }

        if ($this->container['path'] === null) {
            $invalidProperties[] = "'path' can't be null";
        }
        if ($this->container['created_at'] === null) {
            $invalidProperties[] = "'created_at' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string $id id
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets from_station_id
     *
     * @return string
     */
    public function getFromStationId()
    {
        return $this->container['from_station_id'];
    }

    /**
     * Sets from_station_id
     *
     * @param string $from_station_id from_station_id
     *
     * @return self
     */
    public function setFromStationId($from_station_id)
    {
        if (is_null($from_station_id)) {
            throw new \InvalidArgumentException('non-nullable from_station_id cannot be null');
        }
        $this->container['from_station_id'] = $from_station_id;

        return $this;
    }

    /**
     * Gets to_station_id
     *
     * @return string
     */
    public function getToStationId()
    {
        return $this->container['to_station_id'];
    }

    /**
     * Sets to_station_id
     *
     * @param string $to_station_id to_station_id
     *
     * @return self
     */
    public function setToStationId($to_station_id)
    {
        if (is_null($to_station_id)) {
            throw new \InvalidArgumentException('non-nullable to_station_id cannot be null');
        }
        $this->container['to_station_id'] = $to_station_id;

        return $this;
    }

    /**
     * Gets analytic_code
     *
     * @return string
     */
    public function getAnalyticCode()
    {
        return $this->container['analytic_code'];
    }

    /**
     * Sets analytic_code
     *
     * @param string $analytic_code analytic_code
     *
     * @return self
     */
    public function setAnalyticCode($analytic_code)
    {
        if (is_null($analytic_code)) {
            throw new \InvalidArgumentException('non-nullable analytic_code cannot be null');
        }
        $this->container['analytic_code'] = $analytic_code;

        return $this;
    }

    /**
     * Gets distance_km
     *
     * @return float
     */
    public function getDistanceKm()
    {
        return $this->container['distance_km'];
    }

    /**
     * Sets distance_km
     *
     * @param float $distance_km distance_km
     *
     * @return self
     */
    public function setDistanceKm($distance_km)
    {
        if (is_null($distance_km)) {
            throw new \InvalidArgumentException('non-nullable distance_km cannot be null');
        }

        if (($distance_km < 0)) {
            throw new \InvalidArgumentException('invalid value for $distance_km when calling Route., must be bigger than or equal to 0.');
        }

        $this->container['distance_km'] = $distance_km;

        return $this;
    }

    /**
     * Gets path
     *
     * @return string[]
     */
    public function getPath()
    {
        return $this->container['path'];
    }

    /**
     * Sets path
     *
     * @param string[] $path Chemin calculé sous forme de liste ordonnée de stations
     *
     * @return self
     */
    public function setPath($path)
    {
        if (is_null($path)) {
            throw new \InvalidArgumentException('non-nullable path cannot be null');
        }
        $this->container['path'] = $path;

        return $this;
    }

    /**
     * Gets created_at
     *
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->container['created_at'];
    }

    /**
     * Sets created_at
     *
     * @param \DateTime $created_at created_at
     *
     * @return self
     */
    public function setCreatedAt($created_at)
    {
        if (is_null($created_at)) {
            throw new \InvalidArgumentException('non-nullable created_at cannot be null');
        }
        $this->container['created_at'] = $created_at;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


